use Test;
use Terminal::Table::Adaptive;
use JSON::Fast;

my $root = $*PROGRAM.parent.parent;

# ---------------------------------------------------------------------------
# Branch-level exactness
# ---------------------------------------------------------------------------

# Branch B: everything fits naturally.
is-deeply fit-columns([10, 10], [3, 3], 20).Array, [10, 10], 'branch B: natural fit';

# Branch C: shrink proportionally; rounding leftover goes to the column that
# still has headroom (single round-robin pass).
my @c = fit-columns([30, 10], [5, 5], 20);
is @c.sum, 20, 'branch C: exact fill';
is @c[0], 14,  'branch C: bigger column takes proportional share';
is @c[1], 6,   'branch C: smaller column keeps its share';

# Branch C: round-robin remainder, several growable columns.
my @d = fit-columns([100, 100, 100, 100], [2, 2, 2, 2], 60);
is @d.sum, 60, 'branch C: round-robin fills available';
is-deeply @d.Array, [15, 15, 15, 15], 'branch C: even split';

# Branch C: leftover cycles more than once when all columns can grow.
# growth = floor(98/294*94) = 31 -> [33,33,33] = 99, leftover 1.
my @e = fit-columns([100, 100, 100], [2, 2, 2], 100);
is-deeply @e.Array, [34, 33, 33], 'branch C: single leftover handed out once';

# Branch A: min widths overflow; rescale from 1, single-pass leftover.
my @a = fit-columns([40, 4], [10, 2], 12);
is @a.sum, 12, 'branch A: exact fill';
is-deeply fit-columns([8, 8, 8], [8, 8, 8], 10).Array, [4, 3, 3],
    'branch A: leftover goes left to right, single pass';

# Branch A: growth proportional to (min - 1).
is-deeply fit-columns([30, 5], [30, 5], 12).Array, [10, 2],
    'branch A: proportional rescale';

# Branch A degenerate: available < n (render-table guards this; fit-columns
# mirrors JS and keeps every column at 1).
is-deeply fit-columns([10, 10, 10], [5, 5, 5], 2).Array, [1, 1, 1],
    'branch A: degenerate available < n';

# ---------------------------------------------------------------------------
# Oracle: 20k deterministic cases generated by the real pi-tui math
# (tools/reference-fit.mjs, extracted verbatim from renderTable()).
# ---------------------------------------------------------------------------

my $oracle-file = "$root/fixtures/fit-oracle.jsonl";
my @cases = $oracle-file.IO.lines.map(*.&from-json);

for @cases.kv -> $i, $case {
    my @w = fit-columns($case<natural>, $case<min>, $case<available>);
    ok @w.Array eqv $case<widths>.Array,
        "oracle case {$i + 1}/@cases.elems (n={$case<n>}, avail={$case<available>})";
}

# ---------------------------------------------------------------------------
# Invariants over the oracle cases (verified to hold for the JS reference:
# 500k random trials, see tools/inv checks during development).
# ---------------------------------------------------------------------------

for @cases.kv -> $i, $case {
    my @w = fit-columns($case<natural>, $case<min>, $case<available>);
    my $n         = $case<n>;
    my $sum-nat   = [+] @($case<natural>);
    my $sum-min   = [+] @($case<min>);
    my $available = $case<available>;

    # Every width is at least 1.
    ok all(@w) >= 1, "inv $i: widths >= 1";

    if $available >= $n && $sum-nat > $available {
        # Branches A/C fill the available cells exactly.
        is ([+] @w), $available, "inv $i: exact fill (A/C)";
    }
    elsif $sum-nat <= $available {
        # Branch B: never wider than natural.
        ok all(@w Z<= @($case<natural>)), "inv $i: width <= natural (B)";
    }
    else {
        # Branch A with available < n: mirrors JS, all 1s.
        is-deeply @w.Array, [1 xx $n], "inv $i: degenerate A";
    }

    if $sum-nat <= $available || $sum-min <= $available {
        # Branches B/C: width <= max(natural, min).
        ok all(^$n).map({ @w[$_] <= max(@($case<natural>)[$_], @($case<min>)[$_]) }),
            "inv $i: width <= max(natural, min) (B/C)";
    }
}

# Monotonicity: making one column's natural width larger never shrinks that
# column (empirically verified against the JS reference, 500k trials).
for ^2000 -> $t {
    my $n = 1 + $t % 7;
    my @min   = (^$n).map: { 1 + ($t * 7 + $_ * 13) % 30 };
    my @nat   = (^$n).map: { @min[$_] + ($t * 3 + $_ * 5) % 50 };
    my $avail = 1 + ($t * 11) % 200;
    my @w1 = fit-columns(@nat, @min, $avail);
    my $j = $t % $n;
    my @nat2 = @nat;
    @nat2[$j] += 1 + $t % 10;
    my @w2 = fit-columns(@nat2, @min, $avail);
    ok @w2[$j] >= @w1[$j], "monotone $t: wider natural col $j, no shrink";
}

done-testing;
