# Golden tests: byte-for-byte parity with the REAL @earendil-works/pi-tui
# Markdown component (fixtures generated by tools/gen-fixtures.mjs, which
# renders fixed GFM inputs through pi-tui with a plain theme).
#
# The Raku side reproduces the pi-tui pipeline for tables:
#   render-table() output, padded to the terminal width like pi's render()
#   does for every line (visibleWidth-based padding).
use Test;
use Terminal::Table::Adaptive;
use JSON::Fast;

my $root = $*PROGRAM.parent.parent;

my @manifest = from-json(slurp("$root/fixtures/manifest.json"));

# Minimal GFM table splitter for the fixture inputs (plain cells, no escaped
# pipes). Returns (header, rows, raw).
sub parse-gfm-table(Str $md) {
    my @lines = $md.lines;
    my sub cells(Str $line) {
        my @c = $line.split('|');
        @c.shift;
        @c.pop;
        @c.map(*.trim).List
    }
    my @header = cells(@lines[0]);
    my @rows;
    my @table-lines = @lines[0 .. 1];
    my $table-is-last = True;
    for @lines[2 .. *] -> $line {
        if $line.trim eq '' {
            $table-is-last = False;
            last;
        }
        @rows.push(cells($line));
        @table-lines.push($line);
    }
    my $raw = @table-lines.join("\n");
    $raw ~= "\n" if $table-is-last;   # marked keeps the trailing newline in token.raw
    (@header, @rows, $raw)
}

for @manifest -> $entry {
    my $name = $entry<name>;
    my $md   = slurp("$root/fixtures/table/{$entry<table>}.md");
    my ($header, $rows, $raw) = parse-gfm-table($md);
    my $width = $entry<width>;

    my @lines = render-table($header, $rows, $width, :$raw);
    if $name eq 'fallback-next-w8' {
        # pi pipeline: table fallback (no blank: next token is 'space'),
        # then the space token itself renders one blank line, then the
        # following paragraph is wrapped. We compose exactly that.
        @lines.push('');
        @lines.append(wrap-cell('text after the table', $width));
    }

    # pi's render() pads every line to the full terminal width.
    my @padded = @lines.map({ $_ ~ (' ' x max(0, $width - visible-width($_))) });

    my @golden = slurp("$root/fixtures/rendered/$name.txt").lines;
    is-deeply @padded.Array, @golden.Array, "golden: $name";
}

done-testing;
